### ISSUE TITLE
Migration to Kotlin 1.1

### ISSUE THREAD

**Issue by stangls** [andrewoma/reakt#11]
Are there any plans to migrate this project to the official Kotlin-JS release (Kotlin 1.1)?
I am strongly interested in using Kotlin for shared code (REST-Client, Business-Logic) inside the browser, an Android app and a desktop application.
Using react for displaying data created by that shared code would be awesome!

**Comment by andrewoma** [comment]
Hi,

There are no plans to update this to 1.1 - it was really a proof on concept.

Both React and Kotlin have moved on to the extent that this should be rewritten.

I'm holding off having another go until incremental compilation is supported by the Kotlin JS backend.
