### ISSUE TITLE
Compile error Kotlin 1.0.0

### ISSUE THREAD

**Issue by serssp** [andrewoma/reakt#3]
flux.kt
Error:(57, 33) Kotlin: Out-projected type 'kotlin.collections.MutableList<out com.github.andrewoma.flux.RegisteredActionHandler<out kotlin.Any?>>' prohibits the use of 'public abstract fun add(element: E): kotlin.Boolean defined in kotlin.collections.MutableList'

**Comment by andrewoma** [comment]
"Fixed", although I'm not convinced about the soundness of flux.kt in general
