### ISSUE TITLE
Kotlin 1.0.2 support

### ISSUE THREAD

**Issue by serssp** [andrewoma/reakt#8]
After update Kotlin to 1.0.2, i get error
`
Kotlin.defineRootPackage.com.Kotlin.definePackage.github.Kotlin.definePackage.andrewoma.Kotlin.definePackage.react.Kotlin.definePackage.ComponentRenderer.Kotlin.createTrait.render @   com.github.andrewoma.js:233
reactComponentSpec.render   @   reakt-bridge.js:36
ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @   react.js:5941`

generated js code

```
ComponentRenderer: Kotlin.createTrait(null,  {
              render: function () {
                var tmp$0;
                var root = new _.com.github.andrewoma.react.ComponentRenderer.render$f(_.com.github.andrewoma.react.ComponentRenderer.render$f.f);
                this.render_sx5o3u$(root);
                _.com.github.andrewoma.react.check_8kj6y5$(root.children.size <= 1, 'React only supports one (or zero) root components');
                if (root.children.isEmpty())
                  return null;
                return Kotlin.isType(tmp$0 = root.children.get_za3lpa$(0).transform(), ReactElement) ? tmp$0 : Kotlin.throwCCE();
              }
            }
```

**Comment by serssp** [comment]
there is the problem
`return Kotlin.isType(tmp$0 = root.children.get_za3lpa$(0).transform(), ReactElement) ? tmp$0 : Kotlin.throwCCE();`
i solve this by change return value of ComponentRenderer.render() to Any instead ReactElement<*>. 
Is that correct?

**Comment by andrewoma** [comment]
Quite possibly. I vaguely recall react components can render simple strings. 

At this point I'm happy enough to accept a pull request where the build works and the to-do demo isn't broken

**Comment by andrewoma** [comment]
Thanks for the pull request!
